import type { Metadata } from 'next'
import { Geist, Geist_Mono, Roboto } from 'next/font/google'
import './globals.css'
import { ToastContainer } from 'react-toastify'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'], // Escolha os pesos necessários
  subsets: ['latin'],
  style: ['normal', 'italic'], // (Opcional) Para incluir estilos como itálico
})

export const metadata: Metadata = {
  title: 'E-book Reader',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased h-screen w-screen bg-zinc-900 text-zinc-50`}
      >
        {children}
        <ToastContainer />
      </body>
    </html>
  )
}
